folio-org/folio-tools

generate-api-docs/generate_api_docs.py
This is stage one of improvements. See notes at [FOLIO-1253](https://issues.folio.org/browse/FOLIO-1253).
=> FOLIO-1253 improve generate api docs

generate-api-docs/README.md, generate-api-docs/generate_api_docs.py
Fix error introduced to local test mode.
Commence handling RAML 1.0
=> FOLIO-1253 improve generate api docs 2

README.md, lint-raml/.editorconfig, lint-raml/CONTRIBUTING.md, lint-raml/LICENSE, lint-raml/README.md, lint-raml/lint-raml-cop.sh, lint-raml/package.json
Moving mod-notes/scripts/lint-raml-cop.sh to folio-tools/lint-raml and enable universal use.
=> FOLIO-1264 lint-raml-cop.sh

generate-api-docs/README.md, generate-api-docs/generate_api_docs.py
Enable local use too.
Default is CWD, or use --input option.
Also general code cleanup.
Also now not doing git clone, so faster for CI.
=> FOLIO-1253 improve generate-api-docs 5

generate-api-docs/generate_api_docs.py
Better way determine repo_name
=> FOLIO-1253 improve generate-api-docs 7

generate-api-docs/generate_api_docs.py
Tidy.
Fix recently introduced bug with processing multiple docsets per repo, i.e. shared raml repo.
=> FOLIO-1253 improve generate-api-docs 8

jenkins-slave-docker/Dockerfile
See notes at [FOLIO-1027](https://issues.folio.org/browse/FOLIO-1027) today.
=> FOLIO-1027 ci lint-raml-cop

lint-raml/lint_raml_cop.py
=> FOLIO-1027 ci lint-raml-cop 2

generate-api-docs/generate_api_docs.py
Get Major.Minor from ModuleDescriptor.
Save copy of current head output to that sub-directory.
=> FOLIO-1392 generate api docs each version

generate-api-docs/generate_api_docs.py
Some have no MD so get from POM.
=> FOLIO-1392 generate api docs each version 2

generate-api-docs/generate_api_docs.py
=> FOLIO-1392 generate api docs each version 3

lint-raml/lint_raml_cop.py
Simplify script following RMB-203
For RMBv20+ there is now no need to copy to temp_dir to mangle schema $ref
The schema $ref can now be a pathname
=> FOLIO-1399 lint-raml rmb20 2

lint-raml/README.md, lint-raml/lint_raml_cop.py
When use validate trait,
then declare “errors” schema
=> RMB-198 lint-raml rmb20

lint-raml/lint_raml_cop.py
Try to determine why odd failure with raml-module-builder lint-raml
Show the sha1 of raml-util
=> RMB-198 lint-raml rmb20 2

generate-api-docs/generate_api_docs.py
Quick fix for RMBv20 does not have auth.raml
Later add better handling.
=> RMB-227 notify missing auth.raml

generate-api-docs/generate_api_docs.py
=> FOLIO-1253 improve generate api docs 3

lint-raml/lint_raml_cop.py
If config missing use default
Ensure no old traits if v1
=> FOLIO-1027 improve lint raml

lint-raml/lint_raml_cop.py, lint-raml/yarn.lock
Fix error assessing property description.
Tidy.
Update yarn.lock
=> FOLIO-1447 lint raml schema descriptions 2

lint-raml/lint_raml_cop.py
Utilise config schemaDirectory for non-standard
Some raml spaces are different (e.g. mod-configuration)
so utilise api.yml "schemaDirectory" if needed
otherwise look under default configuration.
=> FOLIO-1447 lint raml schema descriptions 4

lint-raml/README.md, lint-raml/lint_raml_cop.py, lint-raml/yarn.lock
Use jq to recursively assess JSON.
=> FOLIO-1447 lint-raml all schema properties descriptions

lint-raml/lint_raml_cop.py
i.e. missing a colon in a schema/trait declaration.
For the 1.0 files, the YAML parser does report broken declarations,
but for 0.8 files, it does not. So need to explicitly verify.
=> FOLIO-1447 Handle poor RAML formatting in 0.8 files

lint-raml/lint_raml_cop.py
Enable comparison between repeated runs.
=> FOLIO-1447 lint-raml sort missing schema descriptions

lint-raml/lint_raml_cop.py, lint-raml/yarn.lock
They were being avoided because this area has different directory structure.
=> FOLIO-1447 Investigate schemas top-level shared raml repo

lint-raml/lint_raml_cop.py
Enables to defer assessment of JSON schema descriptions.
=> FOLIO-1447 add option --validate-only

generate-api-docs/generate_api_docs.py, lint-raml/lint_raml_cop.py, lint-raml/yarn.lock
For data-import-raml-storage and acq-models
schemasOnly: true
MODDATAIMP-44
=> FOLIO-1447 Enable apidocs config to have no ramls

generate-api-docs/find_new_ramls.py, generate-api-docs/verify-config-apidocs.sh
and add accompanying verify-config-apidocs.sh to clone/update the repos, then run it.
=> FOLIO-1253 Improve find_new_ramls for local use

lint-raml/lint_raml_cop.py
Better handling of YAML and HTTP exceptions.
=> FOLIO-1497 lint-raml: improve handling of configuration

generate-api-docs/README.md, generate-api-docs/find_new_ramls.py, generate-api-docs/generate_api_docs.py
Better handle broken YAML.
Clarify some documentation.
=> FOLIO-1253 generate-api-docs: improve handling of configuration

kubernetes-utilities/ci-cleanup/Dockerfile, kubernetes-utilities/ci-cleanup/README.md, kubernetes-utilities/ci-cleanup/cleanup-job.yml, kubernetes-utilities/ci-cleanup/kube-cleanup.py
Adds cleanup script that can be run from a workstation or in the kubernetes cluster. A Dockerfile and example kubernetes cron job are included for the latter.
=> Folio 2194

lint-raml/lint_raml_cop.py
Consistently ordered error output messages
=> FOLIO-1497 lint-raml: sorted processing of raml and schema files

.gitignore, interface-dependents/collect-interface-dependents.py
Introduces a python script that uses an existing FOLIO environment to identify the modules which are dependent upon an interface
=> Interface dependents

jenkins-slave-docker/Dockerfile, jenkins-slave-docker/NEWS.md, jenkins-slave-docker/README.md
=> update to node 10

folio-java-docker/openjdk8/Dockerfile.alpine-jre-openjdk8
Adds new image folioci/alpine-jre-openjdk8
=> FOLIO-2334 FOLIO-2358 container memory

lint-raml/yarn.lock
and z-schema-4.2.2
and associated dependencies
=> FOLIO-1497 lint-rail: Update yarn.lock raml-1-parser 1.1.61

lint-raml/lint_raml_cop.py
=> FOLIO-2539 lint-raml: Avoid some specific errors

jenkins-slave-docker/Dockerfile, jenkins-slave-docker/NEWS.md, jenkins-slave-docker/README.md
See notes at [FOLIO-2561](https://issues.folio.org/browse/FOLIO-2561).
=> FOLIO-2561 update jenkins-slave-all

folio-java-docker/openjdk11/README.md
Adjust example Dockerfile to be similar to existing files, minimise changes.
=> FOLIO-2429 docker image jdk11, tweak README

lint-raml/lint_raml_cop.py, lint-raml/yarn.lock
Also avoid more JSON circular references FOLIO-2539
mod-source-record-storage
=> FOLIO-1497 lint-raml dependencies

add-users/add-users.js
Instead of assigning a permission-set's permissions to users one-by-one,
just, you know, _assign the pset to the user_. That's kinda why we're
creating psets in the first place!
=> add users by pset

add-users/add-users.js
* Users need to have service points assigned in order to conduct many
operations. This script now assigns all available service points to each
user as part of the user-creation process.
* Ignore case when searching for matching permissions
* Leave `permissionName` in place when updating existing psets.
=> add service-points to users

add-users/add-users.js
Support non-https URLs by accepting `--okapi` with a URL like
`http://...`. (Or https URLs like `https://...` if you just like typing
`--okapi https...` instead of `--hostname` because it's more fun.)
=> support --okapi in addition to --hostname

generate-api-docs/README.md, generate-api-docs/deref-schema.js, generate-api-docs/generate_api_docs.py, generate-api-docs/package.json, lint-raml/lint_raml_cop.py, lint-raml/yarn.lock
See [FOLIO-2855](https://issues.folio.org/browse/FOLIO-2855)
=> FOLIO-2855: generate-api-docs: dereference parent JSON schema

api-lint/api_lint.py, api-lint/yarn.lock
amf-client-js 4.6.0 (was 4.5.0)
=> FOLIO-2893 api-lint: upgrade amf-client-js to v4.6.0

api-schema-lint/api_schema_lint.py
recent drafts dropped the trailing hash
=> FOLIO-2917 api-schema-lint: Relax schema keyword detection

clear-loans/DAO.js, clear-loans/README.md, clear-loans/index.js
Trap more errors and continue operating rather than throwing out to the
main loop and quitting. Many errors are transient, or they affect only a
single record and therefore should not abort the entire script.
=> recover from errors instead of exiting

api-schema-lint/api_schema_lint.py
not recognised in OAS 3.0 FOLIO-2948
=> FOLIO-2917 Disable ensure $schema keyword

parse-matrix/README.md, parse-matrix/package-lock.json, parse-matrix/package.json, parse-matrix/parse-matrix, parse-matrix/parse-matrix.bat, parse-matrix/parse-matrix.js
Extract ../jspam's module-responsibility matrix parser so it can be run
stand-alone.
=> output module-responsibility matrix as JSON

add-users/psets/erm-admin.json, add-users/psets/erm-manager.json, add-users/psets/erm-observer.json, add-users/psets/erm-staff.json
Adding the new "Dashboard: Manage dashboard" permission for the erm- users
=> Add Dashboard perms for ERM users

jenkins-slave-docker/NEWS.md
=> FOLIO-3382 jenkins-slave-docker: Update NEWS for 2.9.2

api-lint/api_lint.py, api-lint/package.json, api-lint/yarn.lock
amf-client-js 5.0.8 (was 5.0.2)
=> FOLIO-2893 FOLIO-3486 api-lint: upgrade dependency amf-client-js to v5.0.8

folio-java-docker/openjdk17/Dockerfile, folio-java-docker/openjdk17/NEWS.md, folio-java-docker/openjdk17/README.md, folio-java-docker/openjdk17/run-java.sh
[FOLIO-3499](https://issues.folio.org/browse/FOLIO-3499)
=> FOLIO-3499 folio-java-docker: alpine-jre-openjdk17

jspam/jspam.js
The table structure has changed. AGAIN. And there are some new teams as
well. Handle it all.
=> accommodate recent table structure updates

api-doc/amf.js, api-doc/api_doc.py
To ease generation of documentation index.
[FOLIO-1316](https://issues.folio.org/browse/FOLIO-1316)
=> FOLIO-1316 api-doc: Construct href fragment identifiers

folio-java-docker/openjdk11/NEWS.md, folio-java-docker/openjdk17/NEWS.md
alpine-jre-openjdk17 2.0.4
alpine-jre-openjdk11 1.3.7
=> FOLIO-3552 folio-java-docker: alpine-jre-openjdk: update

api-lint/api_lint.py, api-lint/package.json, api-lint/yarn.lock
amf-client-js 5.2.0 (was 5.0.10)
=> FOLIO-3553 api-lint: upgrade dependency amf-client-js to v5.2.0

api-doc/api_doc.py, api-doc/package.json
amf-client-js 5.2.0 (was 5.0.10)
=> FOLIO-3553 api-doc: upgrade dependency amf-client-js to v5.2.0

add-users/psets/oa-admin.json, add-users/psets/oa-manager.json, add-users/psets/oa-observer.json, add-users/psets/oa-staff.json
Adds psets and users relevant to Open Access request management app
=> Add users with permission sets for Open access (OA)

folio-java-docker/openjdk11/NEWS.md, folio-java-docker/openjdk17/NEWS.md
alpine-jre-openjdk17 2.0.5
alpine-jre-openjdk11 1.3.8
=> FOLIO-3611 folio-java-docker: alpine-jre-openjdk: update

api-lint/api_lint.py, cql_log_parse/cql_log_parse.py, folio-cron-jobs/folioCronService/folioCronService.py, generate-api-docs/find_new_ramls.py, generate-api-docs/generate_api_docs.py, interface-dependents/collect-interface-dependents.py, kubernetes-utilities/ci-cleanup/module-cleanup/kube-cleanup.py, kubernetes-utilities/ci-cleanup/tenant-cleanup/tenant-cleanup.py, kubernetes-utilities/md2kubeyaml/md2kubeyaml.py, lint-raml/lint_raml_cop.py
`flynt **/*.py` -- https://pypi.org/project/flynt
Python f-strings are shorter, faster, and easier to read.  https://www.scivision.dev/python-f-string-speed
=> Python f-strings

api-doc/api_doc.py
major.minor only
Reduce Workflow noise at dev.f.o
=> FOLIO-2898 api-doc: Reduce metadata/generator version

api-doc/api_doc.py, api-doc/package.json
amf-client-js 5.5.3 (was 5.4.6)
=> FOLIO-4011 api-doc: upgrade dependency amf-client-js to v5.5.3

folio-java-docker/README.md, folio-java-docker/openjdk21/Dockerfile, folio-java-docker/openjdk21/NEWS.md, folio-java-docker/openjdk21/README.md, folio-java-docker/openjdk21/run-java.sh
https://folio-org.atlassian.net/browse/FOLIO-4048
I've ran the mod-inventory-storage maven-failsafe-plugin executing the Dockerfile with this openjdk21 base and it succeeds.
=> FOLIO-4048: Add alpine-jre-openjdk21

jenkins-slave-docker/Dockerfile.jammy-java-21, jenkins-slave-docker/NEWS.md
=> FOLIO-4054

api-doc/README.md, api-doc/package.json
tested via mod-permissions mod-users mod-reservoir mod-eusage-reports
=> FOLIO-2898 Enable json-schema-ref-parser v11

add-users/psets/acq-admin.json, add-users/psets/acq-manager.json
=> FOLIO-4250: Add new serials permission to folio-tools/add-users/psets for acq-manager & acq-admin
