folio-org/folio-tools

- jenkins-slave-docker/Dockerfile
Need to use yarn aliases for multiple versions of a dependency
raml2html to enable either RAML-0.8 or RAML-1.0
> FOLIO-1253 generate-api-docs yarn

- generate-api-docs/README.md
- generate-api-docs/generate_api_docs.py
- generate-api-docs/package.json
This is the next stage of improvements. The generate-api-docs now detects whether the input file is RAML-1.0 or RAML-0.8 and uses the relevant version of raml2html.
> FOLIO-1253 improve generate-api-docs 3

- lint-raml/lint_raml_cop.py
The summary is that we need to direct python logging to stdout to enable Jenkins to redirect into an output file.
> FOLIO-1027 ci lint raml cop 5

- lint-raml/README.md
- lint-raml/lint_raml_cop.py
Detect when using RMBv20 and its RAML 1.0
Both pre and post RMB v20 have various peculiarities. Using raml-cop alone is not sufficient.
Assess the RAML and schema files, detect various inconsistencies, then run raml-cop.
Detecting these early helps with understanding the messages from the raml parser.
This version copies sources to a temporary directory, because with today's RMBv20 we need to replace non-standard schema $ref key names with declared pathnames. The RMB-203 might fix that later.
> FOLIO-1399 lint-raml rmb20

- lint-raml/package.json
The new 1.1.46 has trouble with our raml-1.0 rtypes
Go back to 1.1.45 until we can investigate.
Use yarn selective-version-resolutions
>  RMB-227 Use raml-1-parser 1.1.45

- lint-raml/lint_raml_cop.py
Log missing schema descriptions as errors to raise visibility of report. FOLIO-1447
(Still only processing top-level schema properties.)
Processing of acq-models still excluded. MODORDSTOR-12
> FOLIO-1447 lint raml schema descriptions 3

- jenkins-slave-docker/Dockerfile
`ec2_facts` Ansible module has been deprecated, and functionality is now in `ec2_instance_facts`. This module requires boto 3. Towards FOLIO-1558.
> Add boto3 to Docker image for jenkins-slave-docker.

- generate-api-docs/package.json
Display all resource-body divs
> FOLIO-589 generate-api-docs Use folio-org fork raml2html-plain-theme

- lint-raml/README.md
- lint-raml/lint_raml_cop.py
- lint-raml/yarn.lock
Update dependencies: raml-1-parser (raml-js-parser-2) and z-schema, etc.
Separate log messages for processing schema.
Better handle broken YAML.
> FOLIO-1497 Improve lint-raml

- lint-raml/lint_raml_cop.py
- lint-raml/yarn.lock
Only report actual errors.
Also update dependencies:
raml-1-parser v1.1.57 was v1.1.56
z-schema v4.1.1 was v4.1.0
and other supporting dependencies.
> FOLIO-1497 lint-raml: Be a little quiet for lint-raml-schema

- folio-java-docker/openjdk8/Dockerfile.alpine-jre-openjdk8
The full JDK is not needed, only the JRE. This saves 19 MB installed size.
The name Dockerfile.alpine-jre-openjdk8 suggests that it is only JRE.
The other Dockerfile Dockerfile.openjdk8-jre also uses JRE only ("FROM openjdk:8-jre").
> Use JRE (not JDK) for Dockerfile.alpine-jre-openjdk8

- folio-java-docker/openjdk8/README.md
Use "folioci/alpine-jre-openjdk8" instead.
> FOLIO-2367 Deprecate openjdk8-jre-alpine and openjdk8-jre

- folio-java-docker/openjdk8/README.md
openjdk8-jre-alpine and openjdk8-jre will be removed after 2020-04-30
Use "folioci/alpine-jre-openjdk8" instead.
> FOLIO-2367 Emphasise deprecation openjdk8-jre-alpine openjdk8-jre

- lint-raml/yarn.lock
Update to raml-1-parser 1.1.63 and associated dependencies
> FOLIO-1497 lint-raml: Update to raml-1-parser 1.1.63

- jenkins-slave-docker/NEWS.md
See [FOLIO-2572](https://issues.folio.org/browse/FOLIO-2572) and [STCLI-148](https://issues.folio.org/browse/STCLI-148)
> FOLIO-2572 update jenkins-slave-all: Utilise new stripes-cli v1.15.1

- folio-java-docker/openjdk11/Dockerfile
Add curl to base image since we use curl to test health check. Right now, Okapi Java 11 build fails because of that. See comments here https://issues.folio.org/browse/FOLIO-2637?focusedCommentId=84566&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-84566
> Add curl so curl based health check can pass

- README.md
Add missing descriptions to the readme: 
* add-users - Add users with extensive permission sets.
* folio-java-docker - Config files for the Docker image for java-based FOLIO applications.
* interface-dependents - Collect list of modules dependent upon an interface
> add missing doc to README

- jenkins-slave-docker/Dockerfile.agent-focal-java-11
- jenkins-slave-docker/Dockerfile.focal-java-11
- jenkins-slave-docker/Dockerfile.xenial-java-8
`wget --no-check-certificate` disables certificate checks and makes the
installation vulnerable to Man-in-the-middle attacks that might install
malware.
No longer use `--no-check-certificate`.
Make sure that the package ca-certificates is installed. wget needs it
to check certificates.
Dockerfile.xenial-java-8 build fails unless python-dev and libffi-dev
are present.
> FOLIO-2923: Drop --no-check-certificate from wget (MitM attack)

- jenkins-slave-docker/Dockerfile.xenial-java-8
- jenkins-slave-docker/NEWS.md
- jenkins-slave-docker/README.md
> FOLIO-2926: jenkins-slave-docker: Deprecate xenial-java-8

- clear-loans/DAO.js
- clear-loans/README.md
- clear-loans/index.js
- clear-loans/package.json
- okapi-request/README.md
- okapi-request/index.js
- okapi-request/lib/OkapiRequest.js
- okapi-request/package.json
`index.js` node script performs the following actions:
1. check in all outstanding loans (this will clear patron blocks due to
items aged to lost; it will also generate lots of fee/fines records)
2. transfer all outstanding fee/fine records (this will close all open fee/fines)
3. cancel all Page requests with request status Open- Not yet filled
4. anonymize all closed loans
5. delete all closed fee/fines
HTTP request handling is abstracted in `okapi-request`.
Refs [FOLIO-2904](https://issues.folio.org/browse/FOLIO-2904)
> FOLIO-2904 node script to purge loan data

- clear-loans/DAO.js
- clear-loans/index.js
- okapi-request/lib/OkapiRequest.js
This script ran just fine against a small selection of sample data but
when given 10k+ real loans to work through, certain inadequacies became
apparent that are addressed herein.
* change the `accept` header from `application/json` to
`application/json, text/plain` to accommodate certain `DELETE` requests
that require `text/plain`.
* provide `sortby` clauses to `getAll` queries since the order is not
stable otherwise. IOW, `sortby` without an `orderby` clause is pretty
much worthless: it may contain dupes and it is not guaranteed to
actually retrieve all records. Ooooof.
* `checkin()` accepts an optional `resolution` argument that is required
for discharging items that are otherwise rejected as claimed-returned.
* correctly retrieve _all_ non-anonymized closed loans
* correctly retrieve …
> robustness tweaks in okapi-request libraries

- add-users/psets/data-import.json
Per Ann-Marie, add the following permissions to `data-import` to allow for importing of invoices:
* Invoice: Assign acquisitions units to new record
* Invoice: Can view, edit and create new Invoices and Invoice lines
* Invoice: Can view, edit, and delete Invoices and Invoice lines
* Settings (Invoices): Can view and edit settings
> FOLIO-3079 include invoice-import psets in data-import user

- add-users/add-users.js
In order that users can be added with psets that have no displayName
> Store permissionName as additional key for permission lookups

- api-doc/api_doc.py
Some schemas have .yaml extension, so exclude from discovery of api description files.
> FOLIO-2898: api-doc: Exclude schemas directory

- jenkins-slave-docker/Dockerfile.focal-java-11
- jenkins-slave-docker/NEWS.md
* Update Ansible from 2.9.13 to 2.9.21 fixing security issues:
* https://access.redhat.com/security/cve/cve-2021-2022 - Mask default and fallback values for `no_log` module options
* https://access.redhat.com/security/cve/cve-2021-20191 - Various modules missing `no_log` on sensitive module arguments
* https://access.redhat.com/security/cve/cve-2021-20180 - `bitbucket_pipeline_variable` - hide user sensitive information which are marked as `secured` from logging into the console
* https://access.redhat.com/security/cve/cve-2021-20178 - `snmp_facts` - hide user sensitive information such as ``privkey`` and ``authkey`` from logging into the console
* https://access.redhat.com/security/cve/cve-2020-1753 - kubectl connection plugin - now redacts `kubectl_token` and `kubectl_password` in …
> FOLIO-3163: Update jenkins-slave-docker/Dockerfile.focal-java-11

- jspam/README.md
- jspam/jspam.js
When multiple `--label value` flags are passed in, `label` is converted
to an array of strings, but when only one is passed in it remains a
plain string. The Jira API expects an array, hence, `label` must always
be converted to an array.
If it is a string, split it on commas, allowing usage like either
`--label foo --label bar` or `--label foo,bar` to have the same effect.
> correctly handle single label

- clear-loans/README.md
- clear-loans/index.js
- okapi-request/README.md
- okapi-request/lib/OkapiRequest.js
Refactor `okapi-request::getAll` to handle the optional CLI parameters
`--pageSize` (how many items to retrieve in a single request) and
`--streams` (how many requests to run in parallel) to allow for faster
execution with large result sets.
`getAll()` was originally written specifically to handle requests in
series because uncontrolled parallelization in the browser was
overwhelming backend APIs. Here, where scripts are being run in strictly
controlled circumstances by sys-admins who know exactly what they are
doing and exactly what the repercussions will be if they run a jillion
parallel requests, we want to grant them the power to override those
conservative default values.
Also, prefix `console.log` and `console.error` output with a timestamp
to make debugging a wee bit easier.
Refs …
> FOLIO-3248 clear loans fast like rabbit

- jspam/jspam.js
- parse-matrix/README.md
- parse-matrix/parse-matrix.js
Recent updates to the project responsibility matrix HTML markup broke
the parser (header-columns are no longer contained in `<th>`) so we need
to get clever to figure out how to map between the headers specified in
the first row and the data in the remaining rows.
> handle current project-responsibilty-matrix format

- jenkins-slave-docker/Dockerfile.focal-java-11
Updating docker from 20.10.7 to 20.10.11 fixes these security issues:
* https://docs.docker.com/engine/release-notes/
* https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-36221
* https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-39293
* https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-41089
* https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-41091
* https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-41092
* https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-41103
* https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-41190
Updating yarn from 1.22.5 to 1.22.15 gives the latest stable 1.22 release with bugfixes.
> FOLIO-3353: Update jenkins-slave to docker 20.10.11 and yarn 1.22.15

- folio-java-docker/openjdk11/Dockerfile
- folio-java-docker/openjdk11/NEWS.md
Tag image as 1.2.0
[FOLIO-3366](https://issues.folio.org/browse/FOLIO-3366)
> FOLIO-3366 folio-java-docker alpine 3.15.0

- folio-java-docker/openjdk11/Dockerfile
- folio-java-docker/openjdk11/NEWS.md
- folio-java-docker/openjdk11/run-java.sh
To reduce the folioci/alpine-jre-openjdk11 container size from 174 MB to 134 MB switch
from https://github.com/openjdk/jdk11u to OpenJDK Adoptium (Eclipse Temurin)
https://github.com/adoptium/containers = https://adoptium.net/ = https://hub.docker.com/_/eclipse-temurin
Setting securerandom.source=file:/dev/urandom is no longer needed because
this is the default for alpine:3.15.0.
The change in run-java.sh is copied from
https://github.com/fabric8io-images/java/blob/master/images/alpine/openjdk11/jre/run-java.sh
OpenSSL requires libc6-compat in Alpine:
https://issues.folio.org/browse/FOLIO-3406
> FOLIO-3405: OpenJDK Adoptium (Eclipse Temurin) for alpine-jre-openjdk11

- kubernetes-utilities/ci-cleanup/module-cleanup/Dockerfile
- kubernetes-utilities/ci-cleanup/tenant-cleanup/Dockerfile
- kubernetes-utilities/folio-ansible-runner/Dockerfile
- kubernetes-utilities/md2kubeyaml/Dockerfile
- vufind-indexer/Dockerfile
The Docker containers based on the python:alpine image should upgrade these packages:
Upgrade expat from 2.4.3-r0 to 2.4.4-r0 fixing integer overflows:
* https://nvd.nist.gov/vuln/detail/CVE-2022-23852
* https://nvd.nist.gov/vuln/detail/CVE-2022-23990
Upgrade libuuid from 2.37.2-r1 to 2.37.4-r0 fixing util-linux:
* https://nvd.nist.gov/vuln/detail/CVE-2021-3995 = https://github.com/util-linux/util-linux/commit/f3db9bd609494099f0c1b95231c5dfe383346929
* https://nvd.nist.gov/vuln/detail/CVE-2021-3996 = https://github.com/util-linux/util-linux/commit/018a10907fa9885093f6d87401556932c2d8bd2b
* https://nvd.nist.gov/vuln/detail/CVE-2022-0563 = https://github.com/util-linux/util-linux/commit/39a81981ac4b8a1f521db550afc117ccab9548cb
> FOLIO-3420: Upgrade expat, libuuid in python:alpine (CVE-2022-23852)

- folio-java-docker/openjdk11/Dockerfile
Alpine has updated zlib to v1.2.12 that ships with this regression:
When running FOLIO containers in Windows Vagrant box Kafka
messages cause "ZipException: Corrupt GZIP trailer":
https://issues.folio.org/browse/FOLIO-3480
https://github.com/madler/zlib/issues/613
zlib has been fixed on develop branch:
https://github.com/madler/zlib/commit/ec3df00224d4b396e2ac6586ab5d25f673caa4c2
The fix hasn't been released yet.
Until zlib v1.2.13 is available downgrade zlib to the previous
version 1.2.11-r3 that works.
> FOLIO-3480: Downgrade zlib in jre container fixing ZipException

- folio-java-docker/openjdk11/Dockerfile
The stable Alpine branch 3.15 finally got zlib 1.2.12-r1 with the fix:
https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/33688
However, as eclipse-temurin:11-jre-alpine hasn't been upgraded
to the latest zlib version it still contains the buggy
zlib 1.2.12-r0.
Therefore we need to manually run `apk upgrade`.
Testing the Dockerfile after applying this pull request by running
```
docker build -t x .
docker run --rm --entrypoint '/bin/sh' x -c 'apk list zlib'
```
yields
```
zlib-1.2.12-r1 x86_64 {zlib} (Zlib) [installed]
```
with the expected result.
> FOLIO-3487: zlib 1.2.12-r1 fixing ZipException

- jenkins-slave-docker/Dockerfile.jammy-java-17
- jenkins-slave-docker/NEWS.md
- jenkins-slave-docker/README.md
See [FOLIO-3494](https://issues.folio.org/browse/FOLIO-3494)
* Use Ubuntu 22.04 LTS (Jammy Jellyfish) [FOLIO-3478](https://issues.folio.org/browse/FOLIO-3478)
* Use OpenJDK 17.0.3
* Use NodeJS LTS v16 (16.15.0) [FOLIO-3434](https://issues.folio.org/browse/FOLIO-3434)
> FOLIO-3494 jenkins-slave-docker: java-17 with OpenJDK 17 and NodeJS v16

- folio-java-docker/openjdk17/Dockerfile
- folio-java-docker/openjdk17/README.md
Remove curl from folioci/alpine-jre-openjdk-17 for the reasons explained in
https://issues.folio.org/browse/FOLIO-3407
Tracking affected modules: https://github.com/search?q=%22folioci%2Falpine-jre-openjdk17%22&type=code
mod-meta-storage has switched from curl to wget: https://github.com/folio-org/mod-meta-storage/blob/master/Jenkinsfile
> FOLIO-3507: Remove curl from folioci/alpine-jre-openjdk-17

- folio-java-docker/openjdk17/NEWS.md
[FOLIO-3507](https://issues.folio.org/browse/FOLIO-3507)
> FOLIO-3507 folio-java-docker: Add news for 2.0.1 use wget

- kubernetes-utilities/md2kubeyaml/requirements.txt
- vufind-indexer/requirements.txt
Update `urllib3`, `jinja2` to avoid security alerts.
@ihardy, @julianladisch: I noticed a dependabot alert in this repo while updating another script. The updates here are compatible according to semver, but I don't know how to test these scripts to validate that the changes are in fact safe. I would appreciate if you could test it and merge this if it looks good to you.
> update python deps to avoid security alerts

- infrastructure/local/docker-compose.yml
Docker compose complains about networks.default.name not being valid.
As a result docker compose will not run.
Changing the version number to a more recent version, such as 3.7, fixes the problem.
> Update docker compose version in docker-compose.yml.

- api-schema-lint/api_schema_lint.py
Probably misplaced examples are not JSON Schema.
> FOLIO-2917 api-schema-lint: Skip JSON files with no keys

- api-lint/api_lint.py
- api-lint/package.json
- api-lint/yarn.lock
See [FOLIO-3553](https://issues.folio.org/browse/FOLIO-3560) and [FOLIO-3560](https://issues.folio.org/browse/FOLIO-3560). Will await a new AMF version.
> Revert FOLIO-2893 FOLIO-3553 api-lint: upgrade dependency amf-client-js to v5.0.11

- add-users/add-users.js
- folio-java-docker/openjdk11/run-java.sh
- folio-java-docker/openjdk17/run-java.sh
- folio-java-docker/openjdk8/README.md
- folio-java-docker/openjdk8/java-default-options
- kubernetes-utilities/ci-cleanup/module-cleanup/README.md
- kubernetes-utilities/ci-cleanup/tenant-cleanup/tenant-cleanup.py
- lint-raml/lint_raml_cop.py
- okapi-request/lib/OkapiRequest.js
[`codespell --ignore-words-list=inflight,nin,ths .`](https://pypi.org/project/codespell)
> Fix typos discovered by codespell

- api-doc/api_doc.py
- api-doc/package.json
api-doc/deref-schema.js uses vulnerable indirect dependencies.
We only fix the most critical ones.
Upgrade json-ptr from 0.1.1 to >= 3.0.0 fixing Prototype Pollution: https://nvd.nist.gov/vuln/detail/CVE-2021-23509
Upgrade underscore from 1.9.1 to >= 1.12.1 fixing Arbitrary Code Injection: Arbitrary Code Injection: https://nvd.nist.gov/vuln/detail/CVE-2021-23358
Upgrade marked from 1.2.9 to >= 2.0.0 fixing Regular Expression Denial of Service (ReDoS): https://nvd.nist.gov/vuln/detail/CVE-2021-21306
marked cannot be upgrade to >= 4.0.10 to fix more vulnerabilities because the major version bump from 2 to 4 causes a runtime failure.
The three upgrades have been tested with these modules:
* mod-courses
* mod-feesfines
* mod-finance
* mod-finance-storage
* mod-orders
* mod-orders-storage
* …
> FOLIO-3731: api_doc: json-ptr ^3.0.0, marked ^2.0.0, underscore ^1.12.1

- parse-matrix/package-lock.json
- parse-matrix/package.json
- parse-matrix/parse-matrix.js
* The FOLIO responsibility matrix URL changed and its HTML was utterly structured. Handle both.
* Update outdated dependencies.
* Migrate from CJS to ESM. [It is The Way](https://nodejs.org/api/esm.html#introduction).
Refs [FOLIO-3922](https://issues.folio.org/browse/FOLIO-3922)
> FOLIO-3922 handle updated Wiki page

- jenkins-slave-docker/Dockerfile.jammy-java-17
- jenkins-slave-docker/NEWS.md
jenkins-slave-docker/Dockerfile.jammy-java-17
installs the maven version Jammy ships with: 3.6.3-5
Since Orchid FOLIO requires maven 3.8:
https://folio-org.atlassian.net/wiki/spaces/TC/pages/5054392/Orchid#Orchid-Buildtools.1
Solution: Install maven 3.8.8.
> FOLIO-3976: maven 3.8 for folioci/jenkins-slave-all

- api-lint/Pipfile.lock
- api-lint/api_lint.py
- api-lint/package.json
- api-lint/yarn.lock
amf-client-js 5.5.3 (was 5.4.6)
> FOLIO-4011 api-lint: upgrade dependency amf-client-js to v5.5.3

- github-actions-scripts/folioci_npmver.sh
This should work for packages that had thousands of the old job run and very few of the new one (up to a three figure difference, e.g. old #2378 and new #27). Quick looks at several repos appeared to have nothing more extreme than that.
```
old: new_snap_ver=${new_cur_ver}000002378
new: new_snap_ver=${new_cur_ver}0000999927
```
> [STRIPES-930] Update version calculation

- github-actions-scripts/folioci_npmver.sh
We previously added `09000000` to snapshot versions to ensure that new workflow usage would supercede historic old workflow version numbers. However, we need to handle the case where, after the previous change, a module upgrades from the old to new workflows.
> [STRIPES-930] Add new CI version number handling

- github-actions-scripts/folioci_npmver.sh
🤦 #323 had the incorrect bash test condition, resulting in the new_ci version number being used when it should not have been.
Additionally, it seems npm's `semver` is limited to 16 characters per part of the version number. This reduces `new_snap_ver` to fit within that constraint (assuming job_id is <10000):
```
old CI versions:
1090000001
1090000009999
^ patch  ^^^^ build number
^^^^^^^^ constant
new CI versions:
1099990000001
1099990000009999
^ patch     ^^^^ build number
^^^^^^^^^^^ constant
```
Unfortunately, `new_ci` versions have to be this long, as they have to be longer than the old CI versions. We will also need to manually purge the previous attempts (containing `0999999000000`) from Nexus.
> Fix incorrect logic in snapshot version generation

- add-users/psets/user-admin.json
Provide `user-admin` with permission to view, create, and edit users and to set their passwords via developer tools. This will simplify the process of [restoring locked accounts in the reference environments](https://folio-project.slack.com/archives/CFQU1MF61/p1727865874665179?thread_ts=1727863341.432989&cid=CFQU1MF61) where these accounts are used.
@dcrossleyau, it feels like I should ask somebody for permission before adding a privileged user to the reference envs. Are you that person? If not, do you know who is?
> provide a "user-admin" user with appropriate permissions

- github-actions-scripts/folioci_npmver.sh
The previous shell script concatenated a bunch of values together, handling numbers as strings rather than as numbers, eventually leading to a problem where a sufficiently large patch value (ok, it was 9) and sufficiently large build number (>999) combined to create the version string `11.0.9099000000001021`, and the patch value there is greater than 2^53 - 1, which turns out to be the undocumented max as of npm v10.9.2.
This refactor into node preserves most of the existing behavior but manages numbers as numbers so that build numbers like 12, 123, 1234 generate patch values like 1090012, 1090123, 1091234 respectively, and adds some boundary checking (patch values max out at 900, build numbers at 999_999_999 or 9_999_999_999 depending on how the script is called).
Additional details, …
> FOLIO-4362 handle patch values > 8, build values > 999

- github-actions-scripts/folioci_npmver.sh
Provide the absolute path to `folioci_npmver.js`, allowing this script to be called from anywhere. The previous incarnation, PR #350, invoked it simply as `./folioci_npmver.js` and thus operated relative to where the script was being called from, rather than where it is located.
Refs [FOLIO-4370](https://folio-org.atlassian.net/browse/FOLIO-4370)
> FOLIO-4370 provide absolute path to folioci_npmver.js
